language: python

# List of Python and Django version combinations to test
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
env:
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.9.*
  - DJANGO_VERSION=1.8.*

# Some Django / python version combination are not supported
# See https://docs.djangoproject.com/en/1.10/faq/install/#what-python-version-can-i-use-with-django
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.9.*
    - python: 3.3
      env: DJANGO_VERSION=1.10.*

# command to install Django (not in requirements.txt to control version to install)
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

# command to run tests
script: py.test
