language: python

# List of Python and Django version combinations to test
python:
  - "3.5"
  - "2.7"
env:
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.9.*

# command to install Django (not in requirements.txt to control version to install)
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

# command to run tests
script: pytest
