language: python

# List of Python and Django version combinations to test
matrix:
     - python: 3.5
       env: DJANGO_VERSION=1.10.*
     - python: 3.5
       env: DJANGO_VERSION=1.9.*
     - python: 3.5
       env: DJANGO_VERSION=1.8.*
     - python: 3.4
       env: DJANGO_VERSION=1.10.*
     - python: 3.4
       env: DJANGO_VERSION=1.9.*
     - python: 3.4
       env: DJANGO_VERSION=1.8.*
     - python: 3.3
       env: DJANGO_VERSION=1.8.*
     - python: 2.7
       env: DJANGO_VERSION=1.10.*
     - python: 2.7
       env: DJANGO_VERSION=1.9.*
     - python: 2.7
       env: DJANGO_VERSION=1.8.*

# command to install Django (not in requirements.txt to control version to install)
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

# command to run tests
script: py.test
